// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGu2ZbAzd1i1MCo2cere_0CI22QA1N5rI',
    appId: '1:632036317653:web:1aca67b01447562e64455c',
    messagingSenderId: '632036317653',
    projectId: 'rigood-threads',
    authDomain: 'rigood-threads.firebaseapp.com',
    storageBucket: 'rigood-threads.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRFBEBrnfUcanw0JSI3MYt-35KpvcPyIU',
    appId: '1:632036317653:android:50574e9b6061cf6964455c',
    messagingSenderId: '632036317653',
    projectId: 'rigood-threads',
    storageBucket: 'rigood-threads.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXbjjMslY1iu5Um3hKGw7f3gogPHOAZec',
    appId: '1:632036317653:ios:9dd139f30c9da74964455c',
    messagingSenderId: '632036317653',
    projectId: 'rigood-threads',
    storageBucket: 'rigood-threads.appspot.com',
    iosBundleId: 'com.example.threads',
  );
}
